# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{get_shorty}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Louis Gillies"]
  s.date = %q{2010-09-12}
  s.description = %q{Shorten the url of a resource - at present supports active record models and caches the short url to a database column.}
  s.email = %q{louisgillies@yahoo.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HEAD",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config",
     "description",
     "get_shorty.rb",
     "hooks/applypatch-msg.sample",
     "hooks/commit-msg.sample",
     "hooks/post-commit.sample",
     "hooks/post-receive.sample",
     "hooks/post-update.sample",
     "hooks/pre-applypatch.sample",
     "hooks/pre-commit.sample",
     "hooks/pre-rebase.sample",
     "hooks/prepare-commit-msg.sample",
     "hooks/update.sample",
     "info/exclude",
     "lib/get_shorty.rb",
     "lib/providers/bitly.rb",
     "lib/providers/bitly/client.rb",
     "lib/providers/bitly/config.rb",
     "lib/providers/bitly/response.rb",
     "lib/providers/init.rb",
     "spec/active_record_helper.rb",
     "spec/bitly/client_spec.rb",
     "spec/bitly/config_spec.rb",
     "spec/bitly/response_spec.rb",
     "spec/bitly/spec_helper.rb",
     "spec/get_shorty_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/playgood/get_shorty}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Shorten resource urls}
  s.test_files = [
    "spec/active_record_helper.rb",
     "spec/bitly/client_spec.rb",
     "spec/bitly/config_spec.rb",
     "spec/bitly/response_spec.rb",
     "spec/bitly/spec_helper.rb",
     "spec/get_shorty_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.4.2"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rest-client>, [">= 1.4.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rest-client>, [">= 1.4.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.2"])
  end
end

